# Default iot-uni-dongle config
substitutions:
  name: iot-uni-dongle

esphome:
  name: ${name}
  platformio_options:
    upload_speed: 2000000

# Board config
esp8266:
  board: esp12e

# Disable logging via UART
logger:
  baud_rate: 0

# UART config
uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600

# Enable Home Assistant API
api:

# Enable OTA
ota:
  - platform: esphome

# Enable WiFi default access point
wifi:
  ap:
    ssid: "guest AC"
    password: "12345678"

# Enable captive portal
captive_portal:
